export const ENDPOINTS = {
  AGENTS: '/ai/agents',
  AGENT_BY_ID: (agentId) => `/ai/agents/${agentId}`,
  AGENT_GENERATE: (agentId) => `/ai/agents/${agentId}/generate`,
  AGENT_STREAM: (agentId) => `/ai/agents/${agentId}/stream`,
  WORKFLOWS: '/ai/workflows',
  WORKFLOW_RUN: (workflowId) => `/ai/workflows/${workflowId}/run`,
  MEMORY_THREADS: '/ai/memory/threads',
  MEMORY_THREAD_MESSAGES: (threadId) => `/ai/memory/threads/${threadId}/messages`,
  LOGS: '/ai/logs',
  TOOLS: '/tools',
  AUTH_SIGNUP: '/auth/signup',
  AUTH_LOGIN: '/auth/login',
  AUTH_PROFILE: '/auth/profile',
};
